apiVersion: v1
kind: Service
metadata:
  name: mynodejs-service
spec:
  selector:
    app: mynodejs 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31110

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubshellow
  labels:
    app: mynodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynodejs
  template:
    metadata:
      labels:
        app: mynodejs
    spec:
      containers:
      - name: nodeserver
        image: nuwanudara/dockerhub:mykuberneteshello
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
